/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PatientInput = IDL.Record({
  'age' : IDL.Nat,
  'occupation' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'mrdNumber' : IDL.Text,
  'registrationNumber' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
  'address' : IDL.Opt(IDL.Text),
  'gender' : IDL.Text,
  'contactNumber' : IDL.Text,
});
export const CaseHistory = IDL.Record({
  'pgp' : IDL.Text,
  'glassesHistory' : IDL.Text,
  'traumaHistory' : IDL.Text,
  'surgeryHistory' : IDL.Text,
  'allergyHistory' : IDL.Text,
  'familyHistory' : IDL.Text,
  'medicationHistory' : IDL.Text,
  'socialHistory' : IDL.Text,
  'systemicDiseaseHistory' : IDL.Text,
  'consultationHistory' : IDL.Text,
  'chiefComplaint' : IDL.Text,
});
export const AnteriorSegment = IDL.Record({
  'externalExam' : IDL.Text,
  'corneaOD' : IDL.Text,
  'corneaOS' : IDL.Text,
  'scleraOD' : IDL.Text,
  'scleraOS' : IDL.Text,
  'pupillaryEvaluation' : IDL.Text,
  'anteriorChamberOD' : IDL.Text,
  'anteriorChamberOS' : IDL.Text,
  'palpebralFissureHeight' : IDL.Text,
  'lensOD' : IDL.Text,
  'lensOS' : IDL.Text,
  'conjunctivaOD' : IDL.Text,
  'conjunctivaOS' : IDL.Text,
  'pupilOD' : IDL.Text,
  'pupilOS' : IDL.Text,
  'ocularAdnexaOD' : IDL.Text,
  'ocularAdnexaOS' : IDL.Text,
  'irisOD' : IDL.Text,
  'irisOS' : IDL.Text,
});
export const SpecialTests = IDL.Record({
  'tonometryMethod' : IDL.Text,
  'tbutOD' : IDL.Text,
  'tbutOS' : IDL.Text,
  'gonioscopy' : IDL.Text,
  'tonometryOD' : IDL.Text,
  'tonometryOS' : IDL.Text,
  'dilationInstructions' : IDL.Text,
  'tonometryTime' : IDL.Text,
  'otherProcedures' : IDL.Text,
  'roplasOD' : IDL.Text,
  'roplasOS' : IDL.Text,
  'schirmerOD' : IDL.Text,
  'schirmerOS' : IDL.Text,
  'syringingOD' : IDL.Text,
  'syringingOS' : IDL.Text,
});
export const Diagnosis = IDL.Record({
  'learningNotes' : IDL.Text,
  'intervention' : IDL.Text,
  'diagnosis' : IDL.Text,
});
export const VisualAcuity = IDL.Record({
  'newCorrectionODVa' : IDL.Text,
  'newCorrectionOSVa' : IDL.Text,
  'nearOD' : IDL.Text,
  'nearOS' : IDL.Text,
  'pinholeOD' : IDL.Text,
  'pinholeOS' : IDL.Text,
  'distanceOD' : IDL.Text,
  'distanceOS' : IDL.Text,
  'unaidedOD' : IDL.Text,
  'unaidedOS' : IDL.Text,
  'newCorrectionOD' : IDL.Text,
  'newCorrectionOS' : IDL.Text,
  'objectiveRefraction' : IDL.Text,
  'previousGlasses' : IDL.Text,
  'subjectiveRefraction' : IDL.Text,
});
export const ClinicalExam = IDL.Record({
  'eom' : IDL.Text,
  'keratometryComments' : IDL.Text,
  'npcSubjective' : IDL.Text,
  'colorVisionOD' : IDL.Text,
  'colorVisionOS' : IDL.Text,
  'keratometryHorizontal' : IDL.Text,
  'wfdt' : IDL.Text,
  'npaOD' : IDL.Text,
  'npaOS' : IDL.Text,
  'npaOU' : IDL.Text,
  'stereopsis' : IDL.Text,
  'keratometryVertical' : IDL.Text,
  'coverTest' : IDL.Text,
  'npcObjective' : IDL.Text,
});
export const VisitInput = IDL.Record({
  'caseHistory' : CaseHistory,
  'date' : IDL.Int,
  'anteriorSegment' : AnteriorSegment,
  'specialTests' : SpecialTests,
  'diagnosis' : Diagnosis,
  'visualAcuity' : VisualAcuity,
  'clinicalExam' : ClinicalExam,
});
export const Patient = IDL.Record({
  'id' : IDL.Nat,
  'age' : IDL.Nat,
  'occupation' : IDL.Opt(IDL.Text),
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'mrdNumber' : IDL.Text,
  'registrationNumber' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
  'updatedAt' : IDL.Int,
  'address' : IDL.Opt(IDL.Text),
  'gender' : IDL.Text,
  'contactNumber' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
  'specialty' : IDL.Opt(IDL.Text),
});
export const Visit = IDL.Record({
  'id' : IDL.Nat,
  'caseHistory' : CaseHistory,
  'owner' : IDL.Principal,
  'patientId' : IDL.Nat,
  'date' : IDL.Int,
  'anteriorSegment' : AnteriorSegment,
  'specialTests' : SpecialTests,
  'diagnosis' : Diagnosis,
  'visualAcuity' : VisualAcuity,
  'clinicalExam' : ClinicalExam,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createPatient' : IDL.Func([PatientInput], [IDL.Nat], []),
  'createVisit' : IDL.Func([IDL.Nat, VisitInput], [IDL.Nat], []),
  'deletePatient' : IDL.Func([IDL.Nat], [], []),
  'deleteVisit' : IDL.Func([IDL.Nat], [], []),
  'getCallerPatients' : IDL.Func([], [IDL.Vec(Patient)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPatient' : IDL.Func([IDL.Nat], [Patient], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVisit' : IDL.Func([IDL.Nat], [Visit], ['query']),
  'getVisitsByPatient' : IDL.Func([IDL.Nat], [IDL.Vec(Visit)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updatePatient' : IDL.Func([IDL.Nat, PatientInput], [], []),
  'updateVisit' : IDL.Func([IDL.Nat, VisitInput], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PatientInput = IDL.Record({
    'age' : IDL.Nat,
    'occupation' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'mrdNumber' : IDL.Text,
    'registrationNumber' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
    'address' : IDL.Opt(IDL.Text),
    'gender' : IDL.Text,
    'contactNumber' : IDL.Text,
  });
  const CaseHistory = IDL.Record({
    'pgp' : IDL.Text,
    'glassesHistory' : IDL.Text,
    'traumaHistory' : IDL.Text,
    'surgeryHistory' : IDL.Text,
    'allergyHistory' : IDL.Text,
    'familyHistory' : IDL.Text,
    'medicationHistory' : IDL.Text,
    'socialHistory' : IDL.Text,
    'systemicDiseaseHistory' : IDL.Text,
    'consultationHistory' : IDL.Text,
    'chiefComplaint' : IDL.Text,
  });
  const AnteriorSegment = IDL.Record({
    'externalExam' : IDL.Text,
    'corneaOD' : IDL.Text,
    'corneaOS' : IDL.Text,
    'scleraOD' : IDL.Text,
    'scleraOS' : IDL.Text,
    'pupillaryEvaluation' : IDL.Text,
    'anteriorChamberOD' : IDL.Text,
    'anteriorChamberOS' : IDL.Text,
    'palpebralFissureHeight' : IDL.Text,
    'lensOD' : IDL.Text,
    'lensOS' : IDL.Text,
    'conjunctivaOD' : IDL.Text,
    'conjunctivaOS' : IDL.Text,
    'pupilOD' : IDL.Text,
    'pupilOS' : IDL.Text,
    'ocularAdnexaOD' : IDL.Text,
    'ocularAdnexaOS' : IDL.Text,
    'irisOD' : IDL.Text,
    'irisOS' : IDL.Text,
  });
  const SpecialTests = IDL.Record({
    'tonometryMethod' : IDL.Text,
    'tbutOD' : IDL.Text,
    'tbutOS' : IDL.Text,
    'gonioscopy' : IDL.Text,
    'tonometryOD' : IDL.Text,
    'tonometryOS' : IDL.Text,
    'dilationInstructions' : IDL.Text,
    'tonometryTime' : IDL.Text,
    'otherProcedures' : IDL.Text,
    'roplasOD' : IDL.Text,
    'roplasOS' : IDL.Text,
    'schirmerOD' : IDL.Text,
    'schirmerOS' : IDL.Text,
    'syringingOD' : IDL.Text,
    'syringingOS' : IDL.Text,
  });
  const Diagnosis = IDL.Record({
    'learningNotes' : IDL.Text,
    'intervention' : IDL.Text,
    'diagnosis' : IDL.Text,
  });
  const VisualAcuity = IDL.Record({
    'newCorrectionODVa' : IDL.Text,
    'newCorrectionOSVa' : IDL.Text,
    'nearOD' : IDL.Text,
    'nearOS' : IDL.Text,
    'pinholeOD' : IDL.Text,
    'pinholeOS' : IDL.Text,
    'distanceOD' : IDL.Text,
    'distanceOS' : IDL.Text,
    'unaidedOD' : IDL.Text,
    'unaidedOS' : IDL.Text,
    'newCorrectionOD' : IDL.Text,
    'newCorrectionOS' : IDL.Text,
    'objectiveRefraction' : IDL.Text,
    'previousGlasses' : IDL.Text,
    'subjectiveRefraction' : IDL.Text,
  });
  const ClinicalExam = IDL.Record({
    'eom' : IDL.Text,
    'keratometryComments' : IDL.Text,
    'npcSubjective' : IDL.Text,
    'colorVisionOD' : IDL.Text,
    'colorVisionOS' : IDL.Text,
    'keratometryHorizontal' : IDL.Text,
    'wfdt' : IDL.Text,
    'npaOD' : IDL.Text,
    'npaOS' : IDL.Text,
    'npaOU' : IDL.Text,
    'stereopsis' : IDL.Text,
    'keratometryVertical' : IDL.Text,
    'coverTest' : IDL.Text,
    'npcObjective' : IDL.Text,
  });
  const VisitInput = IDL.Record({
    'caseHistory' : CaseHistory,
    'date' : IDL.Int,
    'anteriorSegment' : AnteriorSegment,
    'specialTests' : SpecialTests,
    'diagnosis' : Diagnosis,
    'visualAcuity' : VisualAcuity,
    'clinicalExam' : ClinicalExam,
  });
  const Patient = IDL.Record({
    'id' : IDL.Nat,
    'age' : IDL.Nat,
    'occupation' : IDL.Opt(IDL.Text),
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'mrdNumber' : IDL.Text,
    'registrationNumber' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
    'updatedAt' : IDL.Int,
    'address' : IDL.Opt(IDL.Text),
    'gender' : IDL.Text,
    'contactNumber' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
    'specialty' : IDL.Opt(IDL.Text),
  });
  const Visit = IDL.Record({
    'id' : IDL.Nat,
    'caseHistory' : CaseHistory,
    'owner' : IDL.Principal,
    'patientId' : IDL.Nat,
    'date' : IDL.Int,
    'anteriorSegment' : AnteriorSegment,
    'specialTests' : SpecialTests,
    'diagnosis' : Diagnosis,
    'visualAcuity' : VisualAcuity,
    'clinicalExam' : ClinicalExam,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createPatient' : IDL.Func([PatientInput], [IDL.Nat], []),
    'createVisit' : IDL.Func([IDL.Nat, VisitInput], [IDL.Nat], []),
    'deletePatient' : IDL.Func([IDL.Nat], [], []),
    'deleteVisit' : IDL.Func([IDL.Nat], [], []),
    'getCallerPatients' : IDL.Func([], [IDL.Vec(Patient)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPatient' : IDL.Func([IDL.Nat], [Patient], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVisit' : IDL.Func([IDL.Nat], [Visit], ['query']),
    'getVisitsByPatient' : IDL.Func([IDL.Nat], [IDL.Vec(Visit)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updatePatient' : IDL.Func([IDL.Nat, PatientInput], [], []),
    'updateVisit' : IDL.Func([IDL.Nat, VisitInput], [], []),
  });
};

export const init = ({ IDL }) => { return []; };