/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AnteriorSegment {
  'externalExam' : string,
  'corneaOD' : string,
  'corneaOS' : string,
  'scleraOD' : string,
  'scleraOS' : string,
  'pupillaryEvaluation' : string,
  'anteriorChamberOD' : string,
  'anteriorChamberOS' : string,
  'palpebralFissureHeight' : string,
  'lensOD' : string,
  'lensOS' : string,
  'conjunctivaOD' : string,
  'conjunctivaOS' : string,
  'pupilOD' : string,
  'pupilOS' : string,
  'ocularAdnexaOD' : string,
  'ocularAdnexaOS' : string,
  'irisOD' : string,
  'irisOS' : string,
}
export interface CaseHistory {
  'pgp' : string,
  'glassesHistory' : string,
  'traumaHistory' : string,
  'surgeryHistory' : string,
  'allergyHistory' : string,
  'familyHistory' : string,
  'medicationHistory' : string,
  'socialHistory' : string,
  'systemicDiseaseHistory' : string,
  'consultationHistory' : string,
  'chiefComplaint' : string,
}
export interface ClinicalExam {
  'eom' : string,
  'keratometryComments' : string,
  'npcSubjective' : string,
  'colorVisionOD' : string,
  'colorVisionOS' : string,
  'keratometryHorizontal' : string,
  'wfdt' : string,
  'npaOD' : string,
  'npaOS' : string,
  'npaOU' : string,
  'stereopsis' : string,
  'keratometryVertical' : string,
  'coverTest' : string,
  'npcObjective' : string,
}
export interface Diagnosis {
  'learningNotes' : string,
  'intervention' : string,
  'diagnosis' : string,
}
export interface Patient {
  'id' : bigint,
  'age' : bigint,
  'occupation' : [] | [string],
  'owner' : Principal,
  'name' : string,
  'createdAt' : bigint,
  'mrdNumber' : string,
  'registrationNumber' : string,
  'email' : [] | [string],
  'updatedAt' : bigint,
  'address' : [] | [string],
  'gender' : string,
  'contactNumber' : string,
}
export interface PatientInput {
  'age' : bigint,
  'occupation' : [] | [string],
  'name' : string,
  'mrdNumber' : string,
  'registrationNumber' : string,
  'email' : [] | [string],
  'address' : [] | [string],
  'gender' : string,
  'contactNumber' : string,
}
export interface SpecialTests {
  'tonometryMethod' : string,
  'tbutOD' : string,
  'tbutOS' : string,
  'gonioscopy' : string,
  'tonometryOD' : string,
  'tonometryOS' : string,
  'dilationInstructions' : string,
  'tonometryTime' : string,
  'otherProcedures' : string,
  'roplasOD' : string,
  'roplasOS' : string,
  'schirmerOD' : string,
  'schirmerOS' : string,
  'syringingOD' : string,
  'syringingOS' : string,
}
export interface UserProfile {
  'name' : string,
  'email' : [] | [string],
  'specialty' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Visit {
  'id' : bigint,
  'caseHistory' : CaseHistory,
  'owner' : Principal,
  'patientId' : bigint,
  'date' : bigint,
  'anteriorSegment' : AnteriorSegment,
  'specialTests' : SpecialTests,
  'diagnosis' : Diagnosis,
  'visualAcuity' : VisualAcuity,
  'clinicalExam' : ClinicalExam,
}
export interface VisitInput {
  'caseHistory' : CaseHistory,
  'date' : bigint,
  'anteriorSegment' : AnteriorSegment,
  'specialTests' : SpecialTests,
  'diagnosis' : Diagnosis,
  'visualAcuity' : VisualAcuity,
  'clinicalExam' : ClinicalExam,
}
export interface VisualAcuity {
  'newCorrectionODVa' : string,
  'newCorrectionOSVa' : string,
  'nearOD' : string,
  'nearOS' : string,
  'pinholeOD' : string,
  'pinholeOS' : string,
  'distanceOD' : string,
  'distanceOS' : string,
  'unaidedOD' : string,
  'unaidedOS' : string,
  'newCorrectionOD' : string,
  'newCorrectionOS' : string,
  'objectiveRefraction' : string,
  'previousGlasses' : string,
  'subjectiveRefraction' : string,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createPatient' : ActorMethod<[PatientInput], bigint>,
  'createVisit' : ActorMethod<[bigint, VisitInput], bigint>,
  'deletePatient' : ActorMethod<[bigint], undefined>,
  'deleteVisit' : ActorMethod<[bigint], undefined>,
  'getCallerPatients' : ActorMethod<[], Array<Patient>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPatient' : ActorMethod<[bigint], Patient>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVisit' : ActorMethod<[bigint], Visit>,
  'getVisitsByPatient' : ActorMethod<[bigint], Array<Visit>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updatePatient' : ActorMethod<[bigint, PatientInput], undefined>,
  'updateVisit' : ActorMethod<[bigint, VisitInput], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];