/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Patient {
    id: bigint;
    age: bigint;
    occupation?: string;
    owner: Principal;
    name: string;
    createdAt: bigint;
    mrdNumber: string;
    registrationNumber: string;
    email?: string;
    updatedAt: bigint;
    address?: string;
    gender: string;
    contactNumber: string;
}
export interface Diagnosis {
    learningNotes: string;
    intervention: string;
    diagnosis: string;
}
export interface ClinicalExam {
    eom: string;
    keratometryComments: string;
    npcSubjective: string;
    colorVisionOD: string;
    colorVisionOS: string;
    keratometryHorizontal: string;
    wfdt: string;
    npaOD: string;
    npaOS: string;
    npaOU: string;
    stereopsis: string;
    keratometryVertical: string;
    coverTest: string;
    npcObjective: string;
}
export interface AnteriorSegment {
    externalExam: string;
    corneaOD: string;
    corneaOS: string;
    scleraOD: string;
    scleraOS: string;
    pupillaryEvaluation: string;
    anteriorChamberOD: string;
    anteriorChamberOS: string;
    palpebralFissureHeight: string;
    lensOD: string;
    lensOS: string;
    conjunctivaOD: string;
    conjunctivaOS: string;
    pupilOD: string;
    pupilOS: string;
    ocularAdnexaOD: string;
    ocularAdnexaOS: string;
    irisOD: string;
    irisOS: string;
}
export interface PatientInput {
    age: bigint;
    occupation?: string;
    name: string;
    mrdNumber: string;
    registrationNumber: string;
    email?: string;
    address?: string;
    gender: string;
    contactNumber: string;
}
export interface SpecialTests {
    tonometryMethod: string;
    tbutOD: string;
    tbutOS: string;
    gonioscopy: string;
    tonometryOD: string;
    tonometryOS: string;
    dilationInstructions: string;
    tonometryTime: string;
    otherProcedures: string;
    roplasOD: string;
    roplasOS: string;
    schirmerOD: string;
    schirmerOS: string;
    syringingOD: string;
    syringingOS: string;
}
export interface VisualAcuity {
    newCorrectionODVa: string;
    newCorrectionOSVa: string;
    nearOD: string;
    nearOS: string;
    pinholeOD: string;
    pinholeOS: string;
    distanceOD: string;
    distanceOS: string;
    unaidedOD: string;
    unaidedOS: string;
    newCorrectionOD: string;
    newCorrectionOS: string;
    objectiveRefraction: string;
    previousGlasses: string;
    subjectiveRefraction: string;
}
export interface CaseHistory {
    pgp: string;
    glassesHistory: string;
    traumaHistory: string;
    surgeryHistory: string;
    allergyHistory: string;
    familyHistory: string;
    medicationHistory: string;
    socialHistory: string;
    systemicDiseaseHistory: string;
    consultationHistory: string;
    chiefComplaint: string;
}
export interface Visit {
    id: bigint;
    caseHistory: CaseHistory;
    owner: Principal;
    patientId: bigint;
    date: bigint;
    anteriorSegment: AnteriorSegment;
    specialTests: SpecialTests;
    diagnosis: Diagnosis;
    visualAcuity: VisualAcuity;
    clinicalExam: ClinicalExam;
}
export interface UserProfile {
    name: string;
    email?: string;
    specialty?: string;
}
export interface VisitInput {
    caseHistory: CaseHistory;
    date: bigint;
    anteriorSegment: AnteriorSegment;
    specialTests: SpecialTests;
    diagnosis: Diagnosis;
    visualAcuity: VisualAcuity;
    clinicalExam: ClinicalExam;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createPatient(input: PatientInput): Promise<bigint>;
    createVisit(patientId: bigint, input: VisitInput): Promise<bigint>;
    deletePatient(id: bigint): Promise<void>;
    deleteVisit(id: bigint): Promise<void>;
    getCallerPatients(): Promise<Array<Patient>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getPatient(id: bigint): Promise<Patient>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getVisit(id: bigint): Promise<Visit>;
    getVisitsByPatient(patientId: bigint): Promise<Array<Visit>>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updatePatient(id: bigint, input: PatientInput): Promise<void>;
    updateVisit(id: bigint, input: VisitInput): Promise<void>;
}
import type { Patient as _Patient, PatientInput as _PatientInput, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createPatient(arg0: PatientInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createPatient(to_candid_PatientInput_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPatient(to_candid_PatientInput_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createVisit(arg0: bigint, arg1: VisitInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createVisit(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createVisit(arg0, arg1);
            return result;
        }
    }
    async deletePatient(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePatient(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePatient(arg0);
            return result;
        }
    }
    async deleteVisit(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteVisit(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteVisit(arg0);
            return result;
        }
    }
    async getCallerPatients(): Promise<Array<Patient>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerPatients();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerPatients();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPatient(arg0: bigint): Promise<Patient> {
        if (this.processError) {
            try {
                const result = await this.actor.getPatient(arg0);
                return from_candid_Patient_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPatient(arg0);
            return from_candid_Patient_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVisit(arg0: bigint): Promise<Visit> {
        if (this.processError) {
            try {
                const result = await this.actor.getVisit(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVisit(arg0);
            return result;
        }
    }
    async getVisitsByPatient(arg0: bigint): Promise<Array<Visit>> {
        if (this.processError) {
            try {
                const result = await this.actor.getVisitsByPatient(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVisitsByPatient(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n14(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n14(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updatePatient(arg0: bigint, arg1: PatientInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePatient(arg0, to_candid_PatientInput_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePatient(arg0, to_candid_PatientInput_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateVisit(arg0: bigint, arg1: VisitInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateVisit(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateVisit(arg0, arg1);
            return result;
        }
    }
}
function from_candid_Patient_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Patient): Patient {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n10(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    email: [] | [string];
    specialty: [] | [string];
}): {
    name: string;
    email?: string;
    specialty?: string;
} {
    return {
        name: value.name,
        email: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.email)),
        specialty: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.specialty))
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    age: bigint;
    occupation: [] | [string];
    owner: Principal;
    name: string;
    createdAt: bigint;
    mrdNumber: string;
    registrationNumber: string;
    email: [] | [string];
    updatedAt: bigint;
    address: [] | [string];
    gender: string;
    contactNumber: string;
}): {
    id: bigint;
    age: bigint;
    occupation?: string;
    owner: Principal;
    name: string;
    createdAt: bigint;
    mrdNumber: string;
    registrationNumber: string;
    email?: string;
    updatedAt: bigint;
    address?: string;
    gender: string;
    contactNumber: string;
} {
    return {
        id: value.id,
        age: value.age,
        occupation: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.occupation)),
        owner: value.owner,
        name: value.name,
        createdAt: value.createdAt,
        mrdNumber: value.mrdNumber,
        registrationNumber: value.registrationNumber,
        email: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.email)),
        updatedAt: value.updatedAt,
        address: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.address)),
        gender: value.gender,
        contactNumber: value.contactNumber
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Patient>): Array<Patient> {
    return value.map((x)=>from_candid_Patient_n6(_uploadFile, _downloadFile, x));
}
function to_candid_PatientInput_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PatientInput): _PatientInput {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n15(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    email?: string;
    specialty?: string;
}): {
    name: string;
    email: [] | [string];
    specialty: [] | [string];
} {
    return {
        name: value.name,
        email: value.email ? candid_some(value.email) : candid_none(),
        specialty: value.specialty ? candid_some(value.specialty) : candid_none()
    };
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    age: bigint;
    occupation?: string;
    name: string;
    mrdNumber: string;
    registrationNumber: string;
    email?: string;
    address?: string;
    gender: string;
    contactNumber: string;
}): {
    age: bigint;
    occupation: [] | [string];
    name: string;
    mrdNumber: string;
    registrationNumber: string;
    email: [] | [string];
    address: [] | [string];
    gender: string;
    contactNumber: string;
} {
    return {
        age: value.age,
        occupation: value.occupation ? candid_some(value.occupation) : candid_none(),
        name: value.name,
        mrdNumber: value.mrdNumber,
        registrationNumber: value.registrationNumber,
        email: value.email ? candid_some(value.email) : candid_none(),
        address: value.address ? candid_some(value.address) : candid_none(),
        gender: value.gender,
        contactNumber: value.contactNumber
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
